//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int SolicitudId { get; set; }
        public string TipoSolicitud { get; set; }
        public System.DateTime FechaHoraSolicitud { get; set; }
        public bool Atendido { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Eliminado { get; set; }
        public int ProgramadorId { get; set; }
        public int AppId { get; set; }
    
        public virtual App App { get; set; }
        public virtual Programador Programador { get; set; }
    }
}
